name: Completions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  completions:
    name: Completions
    runs-on: ubuntu-latest
    steps:
      - name: Mark completion
        run: echo "Completions check passed."
